### Authorization by token, part 1. Retrieve and save token.
POST {{base_url}}/{{authenticate_endpoint}}
Content-Type: application/json

{
    "username": "BigThink",
    "password": "q(gf#`HI\\,[?k':R\\A*W"
}
> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Submit Authorized lead
POST {{base_url}}/{{partners_endpoint}}/{{partner_name}}/{{leads_endpoint}}
Content-Type: application/json
Access-Token: {{auth_token}}

< bigthink.json
#< ./hcp/rejected_lead_generic.json
#< ./hcp/approval_lead_generic.json
#< ./blv/9780051_2025_07_09-06_47_11_PM.json
#< ./smallbusinessloans/sbl.json
#< ./smallbusinessloans/SBLID-e5c84fbc-b5d1-49c5-b6a9-62fdcb2aa9c6_2025_05_13-05_42_03_PM.json
#< ./Viably/ab4dd7af-8918-49c4-9c58-365e44698ddc_2025_03_11-12_14_21_PM.json
#< ./1West/a0FPZ000002zg1L2AQ_2025_04_16-02_50_24_PM_FAILING.json
#< ./joist/1eac547e-f249-4215-a974-c6d7ae3e4a9d_36982_US_2025_03_14-02_18_43_PM.json
#< ./become/123456789_2025_02_10-10_46_24_AM.json
#< ./Nav/87a0d99b-ac17-40ec-a1f4-3d3547a15988_2025_07_09-11_37_38_PM.json
#< ./InvSmpl/I9wgKTZ6Vt_2025_07_23-01_43_53_AM.json